organization: "pagopa"
# Gathering data takes about 5 minutes per repo
# depending on the age of the repository.
repositories:
  - "dx"
  - "io-infra"
  - "io-wallet"
  - "io-messages"
  - "io-services-cms"
  - "io-auth-n-identity-domain"
  - "io-ipatente"
  - "io-cgn"
  - "io-cdc"
  - "io-sign"
  - "developer-portal"
  - "interop-be-monorepo"
  - "selfcare"
#  - "selfcare-onboarding"
dx_team_members:
  - gunzip
  - lucacavallaro
  - Krusty93
  - kin0992
  - christian-calabrese
  - mamu0
dx_repo: "dx"
