organization: "pagopa"
# Gathering data takes about 5 minutes per repo
# depending on the age of the repository.
repositories:
  - "io-messages"
  - "io-services-cms"
  - "io-auth-n-identity-domain"
  - "dx"
  - "developer-portal"
  - "io-wallet"
  - "io-infra"
  - "io-ipatente"
  - "io-functions-admin"
  - "io-functions-services"
  - "io-functions-app"
#  - "io-cgn"
#  - "selfcare-onboarding"
dx_team_members:
  - gunzip
  - lucacavallaro
  - Krusty93
  - kin0992
  - christian-calabrese
  - mamu0
